permalink: pretty
incremental: true
author: Avery Magnotti
email: averymagnotti@outlook.com
url: https://blog.citrusui.me
description:
  - The clean and simple portfolio of Avery Magnotti (citrusui). I make websites with modern technologies.
twitter: citrusuiblog
github: https://github.com/citrusui/blog
paypal: AveryMagnotti
brand_color: "#e03431"
sass:
  sass_dir: _includes/poole/_sass
  style: :compressed
exclude:
  - node_modules
  - .hound.yml
  - .sass-lint.yml
  - .travis.yml
  - CNAME
  - firebase.json
  - Gemfile
  - Gemfile.lock
  - Guardfile
  - LICENSE.md
  - package.json
  - README.md
gems:
  - jekyll-feed
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap
title: citrusui blog
paginate: 4
paginate_path: "/page/:num/"
