permalink:           pretty

title:               citrusui
tagline:             Blog
flair:               Software and much more.
url:                 https://citrusui.github.io
twitter:             citrusui
paginate:            2
paginate_path:       "/page/:num/"
baseurl:             ""

sass:
  sass_dir:          _sass
  style:            :compressed

author:
  name:              Avery Magnotti
  url:               https://twitter.com/citrusui
  email:             averymagnotti@outlook.com

version:             1.0
github:
  repo:              https://github.com/citrusui/citrusui.github.io

gems:
  - jekyll-paginate
