source 'https://rubygems.org'

gem 'colorator'
gem 'github-pages'
gem 'jekyll'
gem 'jekyll-paginate'
gem 'jekyll-gist'
gem 'kramdown'
gem 'liquid'
gem 'jekyll-sass-converter'
gem 'jekyll-watch'
gem 'mercenary'
gem 'rouge'
gem 'safe_yaml'